kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      group_by: ['alertname', 'job']

      group_wait: 10s
      repeat_interval: 1m
      receiver: discord

    receivers:
    - name: discord
      discord_configs:
      - webhook_url: https://discordapp.com/api/webhooks/1404663736190505102/bqNm4sgoUu-2xrxtRvA4GtdAzEL3PICmsT6H_qLAGD5tdpTc2prHuNc8hQpj9ueR2mue
